### ISSUE TITLE
Automatic translation on add/edit

### ISSUE THREAD

**Issue by guicsou-lw** [manishkatyan/strapi-google-translator#14]
Is it possible to configure strapi to trigger this on every interaction (add/edit) with the collection?

It would also be awesome to have this built in as an option in the configurations.

**Comment by nishekh-e-r** [comment]
Hi, @guicsou-lw 
This can be achieved using strapi life cycle hooks. Currently, this is not in our roadmap. In the future, we will add this feature.

**Comment by darokviana** [comment]
Are there any hooks to call?
