### ISSUE TITLE
Error unexpected token u in JSON at Position 0

### ISSUE THREAD

**Issue by pcc01** [manishkatyan/strapi-google-translator#18]
I suspect this error is a newbie error, but please let me know what I'm doing wrong.

I have created an API Key within strapi and used used the API key from strapi in the  
STRAPI_GOOGLE_TRANSLATE_API_TOKEN=    location and added the google translate services api key as one line after GOOGLE_TRANSLATE_JSON=  
Translator was successfully added to the UI but it does not appear on the collection when I try and translate I get an error as shown in the first image image
![Strapi_translate issue](https://user-images.githubusercontent.com/23404473/227729024-2e256dec-a3ba-4cd8-b5eb-16896b4bfe6b.png)
.
I note that localization appears in the fields but not in the content types.  Any suggestions?
<img width="610" alt="Collection" src="https://user-images.githubusercontent.com/23404473/227755666-84e86300-276a-40ff-bed3-84f84c2375f1.png">
<img width="611" alt="Field_in_collection" src="https://user-images.githubusercontent.com/23404473/227755674-f9c475ba-56d3-4516-b36c-2d56e72ec57d.png">

**Comment by nishekh-e-r** [comment]
Hi, @pcc01.
After adding env did You follow the below step?

After adding environment variables .env files, go to Config > plugins.js > Add the following code snippet.

```
module.exports = ({ env }) => ({

  "strapi-google-translator": {
    enabled: true,
    config: {
      backendUrl: env("STRAPI_BACKEND_URL"),
      apiToken: env("STRAPI_GOOGLE_TRANSLATE_API_TOKEN"),
      googleJson: env("GOOGLE_TRANSLATE_JSON"),
    },
  },
});
```
