### ISSUE TITLE
Throws 400 error while saving translation of the content types consisting relations/components fields

### ISSUE THREAD

**Issue by developerll** [manishkatyan/strapi-google-translator#20]
**Description**
For any content type ( collection or single) that contains a mixture of normal fields such as text, string, and rich text, as well as relational fields like components and relations, the plugin is throwing error with status code 400 while translating the contents. 

**Screenshot of the dashboard**
![dashboard-screeenshot](https://github.com/manishkatyan/strapi-google-translator/assets/135348081/5e3533b6-83ef-4c9d-9fcd-ffc6951cbf62)

**Screenshot of the CLI**
![cmd_screenshot](https://github.com/manishkatyan/strapi-google-translator/assets/135348081/500b8ece-536f-42cd-b6fb-836889f12223)

While debugging further on the error details thrown on CLI it was found that the plugin is trying to save the translation via Strapi API. Then we imitated the Strapi API call from Postman using the same headers, method, and body as seen on that console. It was found that Strapi is throwing a Validation Error of status code 400 with the message "Undefined attribute level operator name". We could see that although the translation is successful, the issue is only while the plugin is trying to save the translated content.

![image](https://github.com/manishkatyan/strapi-google-translator/assets/135348081/89825585-a358-4574-8b29-6e78f997cded)

**Comment by nishekh-e-r** [comment]
@developerll did you add the strapi API token to API calls, and also you can refer installation section to refer to generate the API token [https://www.npmjs.com/package/strapi-google-translator](https://www.npmjs.com/package/strapi-google-translator).

**Comment by nishekh-e-r** [comment]
@developerll The features - translation of “Components.”, and translation of mixed fields - are the features that are beyond the scope of the free version of the plugin.
